# This is a basic workflow to help you get started with Actions

name: MarkDownParse

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo javac MarkdownParse.java 
          echo java Markdownparse my-test.md
          echo java Markdownparse my-test2.md
          echo java Markdownparse my-test3.md
          echo java Markdownparse my-test4.md
          echo java Markdownparse my-test5.md
          echo java Markdownparse test-file.md
          echo java Markdownparse test-file2.md
          echo java Markdownparse test-file3.md
          echo java Markdownparse test-file4.md
          echo java Markdownparse test-file5.md
          echo java Markdownparse test-file6.md
          echo java Markdownparse test-file7.md
          echo java Markdownparse test-file8.md
          echo javac -cp ".;lib\junit-4.13.2.jar;lib\hamcrest-core-1.3.jar" MarkdownParseTest.java
          echo java -cp ".;lib\junit-4.13.2.jar;lib\hamcrest-core-1.3.jar" org.junit.runner.JUnitCore MarkdownParseTest
